apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: mids
  name: mids
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mids
    spec:
      containers:
      - image: midsw205/base:latest
        name: mids
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
status: {}
