apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: myhdfs
  name: myhdfs
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: myhdfs
    spec:
      containers:
      - image: midsw205/cdh-minimal:latest
        name: myhdfs
        resources: {}
      restartPolicy: Always
status: {}
