apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: myspark
  name: myspark
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: myspark
    spec:
      containers:
      - args:
        - bash
        image: midsw205/spark-python:latest
        name: myspark
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
status: {}
